### ISSUE TITLE
Revamping the hydrostatic mass profile product

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/XGA#1260]
Work has already begun on this - it should be quite simple, I wish to revamp the HydrostaticMass profile class so that it reaches feature parity with the entropy profile class (which was reworked some months ago).

That means that you'll be able to create hydrostatic mass profiles from data points as well as fitted models, those data points can be interpolated if desired, and we'll also allow for projected temperature profiles to be passed as an approximation (we already allowed the projected temperature profiles to be fit with the temperature  models if the user desires).

All these changes should make this class much more flexible and useful.

We'll also add some mass profile models to fit to the data driven hydrostatic mass profiles that will be possible (probably just simple NFW to begin with).

**Comment by DavidT3** [comment]
**NOTE that now the actual mass data points in the profile will have the radius uncertainty included in them - the trouble is that the radius 'uncertainty' for the profile points is set by the width of the bins of the input profiles, and whether that is really an 'uncertainty' in this respect I don't know.**

May have to revisit

**Comment by DavidT3** [comment]
Figuring out the right way to include the radius errors in data is doing my head in:

* For model based measurements it is fine, we'll do it the exact same way we already do in the existing HydrostaticMass class.
* For data based profiles without interpolation turned on, I don't know that I can really do include the radius error in the density/temperature realisations - maybe I can in the gradient calculations though?
* For data with interpolation turned on, I _think_ it should be possible.
* When it comes to the actual final mass calculation, there is a radius term in the actual equation, so will always be able to have the radius errors accounted for.

But yes it is a bit of a bloody mess

**Comment by DavidT3** [comment]
**Note to self** - maybe force a refit of models to the temperature and density profiles (if the user goes that route) if the number of parameter samples and the number of samples specified on Hydrostatic mass profile declaration are not the same.

**Comment by DavidT3** [comment]
Initial attempt to include the radii distribution in the density interpolation mode has ended in a HUGE failure, as I killed the kernel. Suspect the current setup is attempting to interpolate 'num_samples'**$\times$**'num_samples'**$\times$**number of radii. Which I think might cause some issues...

**Comment by DavidT3** [comment]
I'm not actually sure I can include the radius distribution in the interpolation stage in the way I'm thinking - aaaargh

**Comment by DavidT3** [comment]
Same deal with the derivatives, don't really think that I can include radius uncertainty, or that it would actually be valid to

**Comment by astrophysics-megan** [comment]
I have suggestions for you. The radial bins aren’t errors so treating them as errors might lead to conceptual disconnect?

Megan
Sent from my iPhone

On Nov 19, 2024, at 1:21 PM, David Turner ***@***.***> wrote:

﻿

Figuring out the right way to include the radius errors in data is doing my head in:

  *   For model based measurements it is fine, we'll do it the exact same way we already do in the existing HydrostaticMass class.
  *   For data based profiles without interpolation turned on, I don't know that I can really do include the radius error in the density/temperature realisations - maybe I can in the gradient calculations though?
  *   For data with interpolation turned on, I think it should be possible.
  *   When it comes to the actual final mass calculation, there is a radius term in the actual equation, so will always be able to have the radius errors accounted for.

But yes it is a bit of a bloody mess

**Comment by DavidT3** [comment]
For entropy and mass profiles, I will add a flag that allows them to contain unphysical values (i.e. negative masses) without erroring, though the default behaviour will still be to throw an error when it detects that.

**Comment by DavidT3** [comment]
Things are beginning to work in principle:

![image](https://github.com/user-attachments/assets/3944939d-c665-4598-bc03-b2f3ac20a50a)

This is the comparison of the previous (orange) calculation and the new class calculation (blue) of hydrostatic mass from SMOOTH MODELS. So they should be identical, the only difference should be the radii at which they are sampled.

**Comment by DavidT3** [comment]
Now for interpolating from data points, again comparing to the original measurement from the smooth models:

![image](https://github.com/user-attachments/assets/dd0328d0-b3e4-4a38-9a12-d6b4620acc78)

**Same plot but 'joined points' plotting mode:**

![image](https://github.com/user-attachments/assets/46dfb88f-6281-4375-b91e-f6d5423ec0be)


Broadly similar, which makes me more confident that the numerical differentiation is doing broadly what I thought it was (the documentation wasn't completely clear whether it wanted some coordinate analogue (i.e. radius - **this is what I tried here**) for the points, or if it wanted the separations between points (**I think I'll try that as well to be safe**).

Obviously the data-pointed derived profile is not as smooth, which was always going to happen - I do wonder however if there is a better way to handle interpolation, especially for the derivatives, I am currently interpolating the density/temperature AND THEN finding the gradient - I wonder if I should find the gradients of the original points and then interpolate that? That feels less valid somehow.

**Comment by DavidT3** [comment]
Implemented an integrated-NFW profile to allow hydro mass profiles to be fit (now that there is a possibility they'll be derived from something other than smooth models). Not going to lie the first fit wasn't a roaring success :joy:

![image](https://github.com/user-attachments/assets/d9bb4287-647c-47fc-a749-b17d7fd94d51)

![image](https://github.com/user-attachments/assets/b2bd97e8-a048-40d1-afef-0e85eeb7793c)

**Comment by DavidT3** [comment]
Might replace any negative mass distribution values with NaN

**Comment by DavidT3** [comment]
Not a _good_ fit, but the fits do actually work as intended now:

![image](https://github.com/user-attachments/assets/cfa09354-87ef-4693-8a97-f3f90935647e)

![image](https://github.com/user-attachments/assets/9394a38c-9b22-4bce-a20a-4be03432f67d)

**Comment by DavidT3** [comment]
New version of the mass calculation function cannot produce results for individual input radii when using anything but smooth model mode.

**Comment by DavidT3** [comment]
Things are working now - I need to stop the user if they are trying to extrapolate with data points, that clearly won't work

**Comment by DavidT3** [comment]
Issue #1271 is sort of related to this and left outstanding, but I am happy with the state of the new mass class, and am closing this issue.
