### ISSUE TITLE
blackbody fit for spectra generation

### ISSUE THREAD

**Issue by letokotleto** [DavidT3/XGA#680]
could you please add a blackbody fit to xspec fits? 👉🏻👈🏻

**Comment by DavidT3** [comment]
Partially related to issue #435, the general xspec fitting capability, but will probably as blackbody is so common I'll probably implement a specific blackbody function

**Comment by DavidT3** [comment]
The last couple of things to do with this issue:
1) Please could you put the lower limit of energy back to 0.3 keV - I know it'll be slightly annoying to have to change it to a lower value when you want to do the fits, but thats the default of the other models (and XCS' default) so I'd rather be consistent.
2) Remember to change the starting temperature to something higher - maybe 1keV as thats the default of the model?  Again I know its a shame you'll have to change it to lower values, but thats something it seems like you still need to play around with anyway.
3) Please could you change the name of start_temperature to start_temp, to be consistent with single_temp_apec's starting temperature parameter.

**Comment by DavidT3** [comment]
I was also thinking of getting you to modify powerlaw and blackbody to support being unabsorbed, but I know you want to pull this into master and say you've finished it, so I'll make it a separate issue and either you or I can do that later.
