### ISSUE TITLE
weird masking for 2XMM J104608.7-594306 star

### ISSUE THREAD

**Issue by letokotleto** [DavidT3/XGA#692]
there are xcs point sources around it that aren't matched and a lot of the emission is removed

**Comment by letokotleto** [comment]
![image](https://user-images.githubusercontent.com/29706282/143301208-109365ea-d809-4f33-9564-5d7895377677.png)
👁👅👁

**Comment by letokotleto** [comment]
where are the axis units on the right?

**Comment by DavidT3** [comment]
I suspect this will be wrapped up in issue #639, which aims to make the point source matching a little more intelligent. XGA currently just finds point sources that the RA-Dec is inside, so anything ever so slightly offset will not be matched to and thus will be removed like this case. 
For **most** point sources this is okay, as they are distant/dim enough to largely just fit inside, but not necessarily for stars as they are big and bright enough that multiple offset point sources could be found

**Comment by DavidT3** [comment]
Here we are, I use a mask with a radius of 30 arcsec centered on the star (with no interlopers removed), and then overlay the XCS regions within that mask, and we see exactly what happened.

![image](https://user-images.githubusercontent.com/17744555/143418893-33d28e4a-e13b-4e12-b7cf-078213062add.png)


regs = src.regions_within_radii(Quantity(0, 'arcsec'), Quantity(30, 'arcsec'), src.ra_dec)
cst_msk = src.get_custom_mask(Quantity(30, 'arcsec'), remove_interlopers=False, )
rt = src.get_combined_ratemaps()

rt.regions = list(regs)
rt.view(mask=cst_msk, zoom_in=True, view_regions=True)

**Comment by DavidT3** [comment]
The solution for this I think is to create a specific Star and StarSample class that has slightly more leeway in terms of the point source regions it considers a match. I don't know whether I should make the distinction that its a local star, though investigating stars in other galaxies is a bit beyond X-ray in most cases atm

**Comment by DavidT3** [comment]
This has now been solved by a new _source_type_match method for Star class. The user can pass in an extra radius to match to point source regions within. The default is 10arcsecs, which for this particular example results in:

![image](https://user-images.githubusercontent.com/17744555/143581840-7837aa09-fa5e-4c6f-bf9d-7d978e3af371.png)
