### ISSUE TITLE
Suggested rewrite of file reading

### ISSUE THREAD

**Issue by tingard** [DavidT3/XGA#8]
https://github.com/DavidT3/XGA/blob/30b6d1e19a58a38014ccc3cf903be7cf3583e8ee/xga/products.py#L259

```python
with fits.open(self.path, mode="readonly", memmap=False) as temp_im:
    self._data = temp_im[0].data.astype('float32')
    if self._data.min() < 0:
        warnings.warn(...)
        np.maximum(self._data, 0, out=self._data)

temp_im.close(verbose=True)
del temp_im
gc.collect()    
```

I'm sure this is probably what you had to start off with, but it achieves what you want with the creation of as few extra variables as possible (so we don't end up with unwanted references).

It's so frustrating that you can't reliably recreate this error...

**Comment by tingard** [comment]
Figured it's better to have one place to discuss this!

**Comment by tingard** [comment]
Thing's I've learnt:

- calling `astype('float32')` will do a byteswap:

```python
print(np.zeros(10).dtype.byteorder)
print(np.zeros(10).byteswap().dtype.byteorder)
print(np.zeros(10).newbyteorder('=').dtype.byteorder)
print(np.zeros(10).newbyteorder('=').byteswap().dtype.byteorder)
print(np.zeros(10).newbyteorder().byteswap().astype('float32').dtype.byteorder)
```
- I don't understand why it wouldn't work

**Comment by DavidT3** [comment]
This rewrite made the code much cleaner, but I then ended up swapping out this code in favour of using an entirely different module to read in fits files, which seems to have sidestepped the segmentation fault errors.
